import type { Metadata } from "next";
import { Geist, Geist_Mono, Graduate, Tourney } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";

const tourney = Tourney({
  weight: "400",
  variable: "--font-tourney",
  subsets: ["latin"],
});

const graduate = Graduate({
  weight: "400",
  variable: "--font-graduate",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${tourney.variable} ${graduate.variable} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
